export const COUNTRY_CODES_OBJ = {
  'AFG': 'Afghanistan',
  'ALB': 'Albania',
  'DZA': 'Algeria',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'ATG': 'Antigua and Barbuda',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BHS': 'Bahamas',
  'BHR': 'Bahrain',
  'BGD': 'Bangladesh',
  'BRB': 'Barbados',
  'BLR': 'Belarus',
  'BEL': 'Belgium',
  'BLZ': 'Belize',
  'BEN': 'Benin',
  'BTN': 'Bhutan',
  'BOL': 'Bolivia',
  'BIH': 'Bosnia and Herzegovina',
  'BWA': 'Botswana',
  'BRA': 'Brazil',
  'BRN': 'Brunei Darussalam',
  'BGR': 'Bulgaria',
  'BFA': 'Burkina',
  'BDI': 'Burundi',
  'CPV': 'Cabo',
  'KHM': 'Cambodia',
  'CMR': 'Cameroon',
  'CAN': 'Canada',
  'CAF': 'Central African Republic',
  'TCD': 'Chad',
  'CHL': 'Chile',
  'CHN': 'China',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'COG': 'Congo',
  'COK': 'Cook Islands',
  'CRI': 'Czech Republic',
  'CIV': 'Côte',
  'HRV': 'Croatia',
  'CUB': 'Cuba',
  'CYP': 'Cyprus',
  'CZE': 'Democratic People\'s Republic of Korea',
  'PRK': 'Democratic Republic of the Congo',
  'COD': 'Dominican Republic',
  'DNK': 'Denmark',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'SLV': 'El Salvador',
  'GNQ': 'Equatorial Guinea',
  'ERI': 'Eritrea',
  'EST': 'Estonia',
  'SWZ': 'Eswatini',
  'ETH': 'Ethiopia',
  'FJI': 'Fiji',
  'FIN': 'Finland',
  'FRA': 'France',
  'GAB': 'Gabon',
  'GMB': 'Gambia',
  'GEO': 'Georgia',
  'DEU': 'Germany',
  'GHA': 'Ghana',
  'GRC': 'Greece',
  'GRD': 'Grenada',
  'GTM': 'Guatemala',
  'GIN': 'Guinea',
  'GNB': 'Guinea- Bissau',
  'GUY': 'Guyana',
  'HTI': 'Haiti',
  'HND': 'Honduras',
  'HUN': 'Hungary',
  'ISL': 'Iceland',
  'IND': 'India',
  'IDN': 'Indonesia',
  'IRN': 'Iran',
  'IRQ': 'Iraq',
  'IRL': 'Ireland',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'JPN': 'Japan',
  'JOR': 'Jordan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KIR': 'Kiribati',
  'KWT': 'Kuwait',
  'KGZ': 'Kyrgyzstan',
  'LAO': 'Lao People\'s Democratic Republic',
  'LVA': 'Latvia',
  'LBN': 'Lebanon',
  'LSO': 'Lesotho',
  'LBR': 'Liberia',
  'LBY': 'Libya',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MDG': 'Madagascar',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MDV': 'Maldives',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MHL': 'Marshall Islands',
  'MRT': 'Mauritania',
  'MUS': 'Mauritius',
  'MEX': 'Mexico',
  'FSM': 'Micronesia',
  'MCO': 'Monaco',
  'MNG': 'Mongolia',
  'MNE': 'Montenegro',
  'MAR': 'Morocco',
  'MOZ': 'Mozambique',
  'MMR': 'Myanmar',
  'NAM': 'Namibia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NLD': 'Netherlands',
  'NZL': 'New Zealand',
  'NIC': 'Nicaragua',
  'NER': 'Niger',
  'NGA': 'Nigeria',
  'NIU': 'Niue',
  'MKD': 'North Macedonia',
  'NOR': 'Norway',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PLW': 'Palau',
  'PAN': 'Panama',
  'PNG': 'Papua New Guinea',
  'PRY': 'Paraguay',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'POL': 'Poland',
  'PRT': 'Portugal',
  'QAT': 'Qatar',
  'KOR': 'Republic of Korea',
  'MDA': 'Republic of Moldova',
  'ROU': 'Romania',
  'RUS': 'Russian Federation',
  'RWA': 'Rwanda',
  'KNA': 'Saint Kitts and Nevis',
  'LCA': 'Saint Lucia',
  'VCT': 'Saint Vincent and the Grenadines',
  'WSM': 'Samoa',
  'SMR': 'San Marino',
  'STP': 'Sao Tome and Principe',
  'SAU': 'Saudi Arabia',
  'SEN': 'Senegal',
  'SRB': 'Serbia',
  'SYC': 'Seychelles',
  'SLE': 'Sierra Leone',
  'SGP': 'Singapore',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SLB': 'Solomon Islands',
  'SOM': 'Somalia',
  'ZAF': 'South Africa',
  'SSD': 'South Sudan',
  'ESP': 'Spain',
  'LKA': 'Sri Lanka',
  'SDN': 'Sudan',
  'SUR': 'Suriname',
  'SWE': 'Sweden',
  'CHE': 'Switzerland',
  'SYR': 'Syrian Arab Republic',
  'TJK': 'Tajikistan',
  'THA': 'Thailand',
  'TLS': 'Timor - Leste',
  'TGO': 'Togo',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TKM': 'Turkmenistan',
  'TUV': 'Tuvalu',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'ARE': 'United Arab Emirates',
  'GBR': 'United Kingdom of Great Britain and Northern Ireland',
  'TZA': 'United Republic of Tanzania',
  'USA': 'United States of America',
  'URY': 'Uruguay',
  'UZB': 'Uzbekistan',
  'VUT': 'Vanuatu',
  'VEN': 'Venezuela',
  'VNM': 'Viet',
  'YEM': 'Yemen',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe'
}

export const COUNTRY_CODES_ARR = [
  'AFG',
  'ALB',
  'DZA',
  'AND',
  'AGO',
  'ATG',
  'ARG',
  'ARM',
  'AUS',
  'AUT',
  'AZE',
  'BHS',
  'BHR',
  'BGD',
  'BRB',
  'BLR',
  'BEL',
  'BLZ',
  'BEN',
  'BTN',
  'BOL',
  'BIH',
  'BWA',
  'BRA',
  'BRN',
  'BGR',
  'BFA',
  'BDI',
  'CPV',
  'KHM',
  'CMR',
  'CAN',
  'CAF',
  'TCD',
  'CHL',
  'CHN',
  'COL',
  'COM',
  'COG',
  'COK',
  'CRI',
  'CIV',
  'HRV',
  'CUB',
  'CYP',
  'CZE',
  'PRK',
  'COD',
  'DNK',
  'DJI',
  'DMA',
  'DOM',
  'ECU',
  'EGY',
  'SLV',
  'GNQ',
  'ERI',
  'EST',
  'SWZ',
  'ETH',
  'FJI',
  'FIN',
  'FRA',
  'GAB',
  'GMB',
  'GEO',
  'DEU',
  'GHA',
  'GRC',
  'GRD',
  'GTM',
  'GIN',
  'GNB',
  'GUY',
  'HTI',
  'HND',
  'HUN',
  'ISL',
  'IND',
  'IDN',
  'IRN',
  'IRQ',
  'IRL',
  'ISR',
  'ITA',
  'JAM',
  'JPN',
  'JOR',
  'KAZ',
  'KEN',
  'KIR',
  'KWT',
  'KGZ',
  'LAO',
  'LVA',
  'LBN',
  'LSO',
  'LBR',
  'LBY',
  'LTU',
  'LUX',
  'MDG',
  'MWI',
  'MYS',
  'MDV',
  'MLI',
  'MLT',
  'MHL',
  'MRT',
  'MUS',
  'MEX',
  'FSM',
  'MCO',
  'MNG',
  'MNE',
  'MAR',
  'MOZ',
  'MMR',
  'NAM',
  'NRU',
  'NPL',
  'NLD',
  'NZL',
  'NIC',
  'NER',
  'NGA',
  'NIU',
  'MKD',
  'NOR',
  'OMN',
  'PAK',
  'PLW',
  'PAN',
  'PNG',
  'PRY',
  'PER',
  'PHL',
  'POL',
  'PRT',
  'QAT',
  'KOR',
  'MDA',
  'ROU',
  'RUS',
  'RWA',
  'KNA',
  'LCA',
  'VCT',
  'WSM',
  'SMR',
  'STP',
  'SAU',
  'SEN',
  'SRB',
  'SYC',
  'SLE',
  'SGP',
  'SVK',
  'SVN',
  'SLB',
  'SOM',
  'ZAF',
  'SSD',
  'ESP',
  'LKA',
  'SDN',
  'SUR',
  'SWE',
  'CHE',
  'SYR',
  'TJK',
  'THA',
  'TLS',
  'TGO',
  'TON',
  'TTO',
  'TUN',
  'TUR',
  'TKM',
  'TUV',
  'UGA',
  'UKR',
  'ARE',
  'GBR',
  'TZA',
  'USA',
  'URY',
  'UZB',
  'VUT',
  'VEN',
  'VNM',
  'YEM',
  'ZMB',
  'ZWE'
]